name: ts2vec
dependencies:
  - pip=22.3.1
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - pandas==1.4.4
    - torch==2.0.1+cu118
    - pytorch-lightning==1.6.*
    - pytorch-lifestream==0.5.2
    - matplotlib==3.7.2
    - scikit-learn==1.3.0
    - lightgbm==4.1.0