name: ts2vec_churn_date

seq_encoder:
  _target_: nn.seq_encoder.ConvSeqEncoder
  trx_encoder:
    _target_: ptls.nn.TrxEncoder
    use_batch_norm_with_lens: True
    norm_embeddings: False
    embeddings_noise: 0.0003
    embeddings: {mcc_code: {in: 345, out: 24}}
    out_of_index: clip
    numeric_values: {
      amount: identity,
      event_time: identity,
      time_delta: identity,
    }
  hidden_size: 1024
  num_layers: 10
  dropout: 0.1

path_to_state_dict: checkpoints/churn/ts2vec/ts2vec_churn_date.pth