name: ts2vec_default_weighted_2_sqrt

seq_encoder:
  _target_: nn.seq_encoder.ConvSeqEncoder
  trx_encoder:
    _target_: nn.trx_encoder.TimeTrxEncoder
    use_batch_norm_with_lens: True
    norm_embeddings: False
    embeddings_noise: 0.003
    embeddings: {mcc_code: {in: 345, out: 16}}
    out_of_index: clip
    numeric_values: {
      amount: identity
    }
  hidden_size: 800
  num_layers: 10
  dropout: 0.1

path_to_folder: checkpoints/default/ts2vec/ts2vec_default_weighted_2_sqrt